apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kuard-v2-pod
  name: kuard-v2-pod
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: "100m"
        memory: "5Gi"
      limits:
        cpu: "500m"
        memory: "5Gi"

