apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    volume: db-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  nfs:
    server: 67.205.161.167
    path: /share

